### ISSUE TITLE
Замечания и пожелания

### ISSUE THREAD

**Issue by KonstantinGeist** [MihaGoHard/Projection-Development#1]
1. Файл Makefile (при использовании CMake), папка CMakeFiles, файл CMakeCache.txt не должны быть в репозитории -- это "артефакты сборки". Во-первых, включать их в репозиторий избыточно, т.к. их всё равно можно перегенерировать при сборке из CMakeLists. Во-вторых, с большой вероятностью на других машинах всё равно придётся удалять эти файлы и пересобирать заново, т.к. артефакт сборки специфичен для конкретного окружения (ОС, архитектура процессора и т.д.) и может не сработать для другого окружения.

2. Папка с названием 00 вызывает вопросы -- она явно скопирована с лабораторных, где это было уместно (нумерация лабороторных), но в данном проекте неуместна.

3. Код и организация проекта должны быть максимально аккуратными (иначе если не соблюдать это правило, то при работе в большой команде ситуация может выйти из-под контроля). В папке textures много мусорных файлов с именами вроде "jdl--RJL3G8 — копия (4) — копия.jpg".

4. В textures.h присутствует дублирование: если ожидается, что все текстуры должны быть smooth, можно было завести метод initSmoothTexture, который бы загружал текстуру и делал её smooth. Глобальные переменные -- ОК для данного проекта, но в идеале следовало бы сделать какой-нибудь TextureManager.

5. Функцию checkCollision в supportFunctions.h можно упростить в ```return firstRect.getGlobalBounds().intersects(secondRect.getGlobalBounds()```

6. Лучше не называть функции словом check..., т.к. семантика не сразу ясна (возвращает bool, кидает исключение, делает assert, резолвит коллизии?). Лучше вместо checkCollision назвать функцию hasCollision или doCollide. Тем более что в соседнем файле функция checkShellCollision как раз-таки не возвращает bool, а внезапно меняет состояние мира.

7. Sollution => Solution

8. Понравилась функция processMainGamePlay -- все шаги обработки как на ладони

9. Есть проблемы с наименованием функций: по названиям checkTankCollisionSetMoveSollution/checkTanksDestroyInitNewTanks сразу неясно, что они делают (первое впечатление -- какое-то нагромождение глаголов). Или, например: константа называется BASE, а функция -- initBird. Следует привести к единому именованию. Также, напр., неясно, что такое sentBarrier/sentBlock ("посланный барьер", "посланный блок"?) Названия вроде checkShellInShellsArr непонятны без чтения кода реализации (более "стандартное" название начиналось бы с "is" или содержало глагол "contain"). В целом основное замечание по проекту -- не сразу понятные названия функций/переменных, но это приходит с опытом.

10. Во многих проектах рекомендуется в блоках if/for/while всегда использовать фигурные скобки (хотя синтаксис C/C++ позволяет обходиться без них для однострочных выражений) -- дело в том, что при параллельной работе в команде, в том числе при мерже из разных веток, часть кода может оказаться вне условия, что приводит к печальным последствиям вроде https://dwheeler.com/essays/apple-goto-fail.html

**Comment by KonstantinGeist** [comment]
11. Фрагменты с ```timeToShow % 5 == 0 && timeToShow != 0)``` в gameProcess.h не сразу ясны, и дублируются, можно было бы выделить в отдельную функцию, чтобы название функции было "говорящим".

12. gameControl и подобные значения можно было бы выделить в enum

13. В функции updateGameControl блоки условий лучше было бы выделить в отдельные функции -- функция слишком большая получилась

14. В функциях drawNum/setLevelNumer/setDigitTexture/calcScoreSetTextures/updateLivesLabels можно было бы ссылаться на массив текстур и находить нужную просто по индексу (вместо switch case)

15. В функции mainMenuKeyboardEvents присутствует закомментированный код. Такое лучше не коммитить в master

16. В функции initBase не очевидно, что особенного в индексах 2 и 1 (с ними идёт проверка для особой логики). Тут не хватает именованных констант.

17. В функции drawExplosions переменная effectInex кажется лишней.

18. В функции updateShells присутствует магическая константа 20.0

19. В функции checkShellCollision, похоже, ошибка: внутри цикла определяется ещё одна переменная с таким же именем currShellDestroyed ("variable shadowing"), и она никак не используется.

20. Присутствует странное форматирование вида ```sf ::Keyboard ::Down``` Ожидалось: ```sf::Keyboard::Down```

21. В checkFieldSetSollution многое можно было бы упростить, вида: ```currTank.moveSolution.canMoveLeft = tankPosition.x > LEFT_FIELD_BORDER;```

22. В функции updatePlayerTank присутствует дублирование, можно было бы сократить.

В остальном довольно неплохо! Код более-менее аккуратный и обладает структурой.

**Comment by MihaGoHard** [comment]
Доработано с учётом замечаний и пожеланий
